"""
schemas/analytics_context.py

Structured payload generated by the Business Analytics Engine and injected into RagService.
"""

from dataclasses import dataclass, field
from typing import List, Dict
from schemas.business_metric import BusinessMetric, MetricCategory

from schemas.dashboard import ChartSeries

@dataclass
class AnalyticsContext:
    """
    Context passed to the LLM containing deterministically computed analytics.
    The LLM uses this to explain the math rather than computing it.
    """
    metrics: List[BusinessMetric] = field(default_factory=list)
    charts: List[ChartSeries] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    
    # Categorized metrics for easier prompt assembly and API responses
    raw_metrics: List[BusinessMetric] = field(default_factory=list)
    derived_kpis: List[BusinessMetric] = field(default_factory=list)
    ratios: List[BusinessMetric] = field(default_factory=list)
    health_indicators: List[BusinessMetric] = field(default_factory=list)
    
    analytics_text: str = ""

    def __post_init__(self):
        """Auto-categorize metrics and build the prompt text."""
        for m in self.metrics:
            if m.metric_category == MetricCategory.RAW:
                self.raw_metrics.append(m)
            elif m.metric_category == MetricCategory.DERIVED:
                self.derived_kpis.append(m)
            elif m.metric_category == MetricCategory.RATIO:
                self.ratios.append(m)
            elif m.metric_category == MetricCategory.HEALTH:
                self.health_indicators.append(m)
                
        self.analytics_text = self._build_analytics_text()

    def _build_analytics_text(self) -> str:
        """
        Constructs the text narrative for the LLM prompt.
        """
        if not self.metrics:
            return "--- BUSINESS ANALYTICS ---\nNo metrics were computed for this query."
            
        lines = ["--- DETERMINISTIC BUSINESS ANALYTICS ---", 
                 "Do not compute these manually. These are exactly calculated metrics.", ""]
        
        if self.health_indicators:
            lines.append("## Business Health")
            for m in self.health_indicators:
                lines.append(f"- {m.metric_name}: {m.metric_value} {m.unit}")
            lines.append("")
            
        if self.ratios:
            lines.append("## Key Ratios")
            for m in self.ratios:
                lines.append(f"- {m.metric_name}: {m.metric_value} {m.unit}")
            lines.append("")
            
        if self.derived_kpis:
            lines.append("## Derived KPIs")
            for m in self.derived_kpis:
                lines.append(f"- {m.metric_name}: {m.metric_value} {m.unit}")
            lines.append("")
            
        if self.raw_metrics:
            lines.append("## Raw Totals")
            for m in self.raw_metrics:
                lines.append(f"- {m.metric_name}: {m.metric_value} {m.unit}")
            lines.append("")
            
        if self.warnings:
            lines.append("## Analytics Warnings")
            for w in self.warnings:
                lines.append(f"- WARNING: {w}")
            lines.append("")
            
        return "\n".join(lines)
